FROM eclipse-temurin:21-jre
WORKDIR /app
COPY target/tarefas-1.0.0.jar app.jar
RUN ./mvnw clean package -DskipTests


FROM eclipse-temurin:21-jre
WORKDIR /app


COPY --from=builder /app/target/*.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]